# SwiftLint configuration for Nidus project

# Disable rules that might block builds
disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try
  - large_tuple
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_parameter_count
  - identifier_name
  
# Only include non-blocking opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  
excluded:
  - Pods
  - DerivedData
  - .build
  - ${PODS_ROOT}
  - ${DERIVED_DATA}
  - Carthage
  - fastlane
  - Nidus.xcodeproj
  - Nidus.xcworkspace
  
# Set all rule violations to warning level only
# This prevents SwiftLint from blocking builds
warning_threshold: 1

# Use xcode reporter for better integration
reporter: "xcode"
